permalink:           pretty

# Setup
title:               'Artificial General Intelligence'
url:                 https://shimon-K.github.io/AGI-Course/
baseurl:             '/AGI-Course'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                Shimon
url:                 https://twitter.com/ShimonKom
github:
  repo:              https://github.com/shimon-K/AGI-Course/

# Custom vars
version:             dlsp20

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "custom"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - en/index.md
  - vendor

################################### English ####################################
prologues:
  - path: en/Introduction/about.md
    sections:
      - path: en/Introduction/Course presentation.md
      - path: en/Introduction/Understanding.md
      - path: en/Introduction/AGI research approach.md
chapters:
  - path: en/Human sciences/01.md
    sections:
      - path: en/Human sciences/01-1.md
      - path: en/Human sciences/01-2.md
      - path: en/Human sciences/01-3.md
      - path: en/Human sciences/01-4.md
  - path: en/Classical AI/01.md
    sections:
      - path: en/Classical AI/01-1.md
      - path: en/Classical AI/01-2.md
      - path: en/Classical AI/01-3.md
      - path: en/Classical AI/01-4.md
      - path: en/Classical AI/01-5.md
  - path: en/Deep Learning/01.md
    sections:
      - path: en/Deep Learning/01-1.md
      - path: en/Deep Learning/01-2.md
      - path: en/Deep Learning/01-3.md
      - path: en/Deep Learning/01-4.md
      - path: en/Deep Learning/01-5.md
      - path: en/Deep Learning/01-6.md
      - path: en/Deep Learning/01-7.md
      - path: en/Deep Learning/01-8.md
      - path: en/Deep Learning/01-9.md
      - path: en/Deep Learning/01-10.md
epilogues:
  - path: en/Finale/end.md

