permalink:           pretty

# Setup
title:               'Artificial General Intelligence'
url:                 https://shimon-K.github.io/AGI-Course/
baseurl:             '/AGI-Course'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                Shimon
url:                 https://twitter.com/ShimonKom
github:
  repo:              https://github.com/shimon-K/AGI-Course/

# Custom vars
version:             dlsp20

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "custom"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - index.md
  - vendor

################################### English ####################################
prologues:
  - path: en/about.md
chapters:
  - path: en/week01/01.md
    sections:
      - path: en/week01/01-1.md
      - path: en/week01/01-2.md
      - path: en/week01/01-3.md
  - path: en/week02/02.md
    sections:
      - path: en/week02/02-1.md
      - path: en/week02/02-2.md
      - path: en/week02/02-3.md
  - path: en/week03/03.md
    sections:
      - path: en/week03/03-1.md
      - path: en/week03/03-2.md
      - path: en/week03/03-3.md
  - path: en/week04/04.md
    sections:
      - path: en/week04/04-1.md
  - path: en/week05/05.md
    sections:
      - path: en/week05/05-1.md
      - path: en/week05/05-2.md
      - path: en/week05/05-3.md
  - path: en/week06/06.md
    sections:
      - path: en/week06/06-1.md
      - path: en/week06/06-2.md
      - path: en/week06/06-3.md
  - path: en/week07/07.md
    sections:
      - path: en/week07/07-1.md
      - path: en/week07/07-2.md
      - path: en/week07/07-3.md
  - path: en/week08/08.md
    sections:
      - path: en/week08/08-1.md
      - path: en/week08/08-2.md
      - path: en/week08/08-3.md
  - path: en/week09/09.md
    sections:
      - path: en/week09/09-1.md
      - path: en/week09/09-2.md
      - path: en/week09/09-3.md
  - path: en/week10/10.md
    sections:
      - path: en/week10/10-1.md
      - path: en/week10/10-2.md
      - path: en/week10/10-3.md
  - path: en/week11/11.md
    sections:
      - path: en/week11/11-1.md
      - path: en/week11/11-2.md
      - path: en/week11/11-3.md
  - path: en/week12/12.md
    sections:
      - path: en/week12/12-1.md
      - path: en/week12/12-2.md
      - path: en/week12/12-3.md
  - path: en/week13/13.md
    sections:
      - path: en/week13/13-1.md
      - path: en/week13/13-2.md
      - path: en/week13/13-3.md
  - path: en/week14/14.md
    sections:
      - path: en/week14/14-1.md
      - path: en/week14/14-2.md
      - path: en/week14/14-3.md
  - path: en/week15/15.md
    sections:
      - path: en/week15/15-1.md
      - path: en/week15/15-2.md
#epilogues:
#  - path: chapters/end.md

